# Generated by Django 3.1.7 on 2021-04-26 14:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('film', '0002_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='language',
            field=models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, to='film.language'),
            preserve_default=False,
        ),
    ]
