# Generated by Django 3.1.7 on 2021-04-26 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actor', '0001_initial'),
        ('film', '0003_film_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='actors',
            field=models.ManyToManyField(to='actor.Actor'),
        ),
    ]
