# Generated by Django 3.1.7 on 2021-06-14 15:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('actor', '0001_initial'),
        ('film', '0004_film_actors'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='film',
            name='actors',
        ),
        migrations.CreateModel(
            name='FilmActor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_update', models.DateField()),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='actor.actor')),
                ('film', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='film.film')),
            ],
        ),
    ]
